<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code);
    $ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width",$code);
    $ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height",$code);
    
    if(!$ratio_width)
        $ratio_width = 300;
    if(!$ratio_height)
        $ratio_height = 400;
?>

<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="block block-list block-viewed">
    <!--<div class="block-title">
        <strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong>
    </div>-->

        <div id="recently-viewed-items">
		<div class="products small-list sidebar-list owl-carousel owl-top-narrow">
        <?php $i=0; foreach ($_products as $_item): ?>
		    <?php
        if(($i%3) == 0){
    ?>
            <div class="item">
    <?php
        }
            $i++;
    ?>
            <div class="item-area">
                        <div class="col-xs-6">
                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image-area"><img src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                        </div>
                        <div class="product-details col-xs-6">
                            <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                            <?php 
                            if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                            ?>
                            <?php 
                                $review_html = $this->getReviewsSummaryHtml($_item, 'short');
                                if($review_html){
                                    echo $review_html;
                                }else{
                            ?>
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:0"></div>
                                    </div>
                                </div>
                            <?php                            
                                }
                            ?>
                            <?php else: ?>
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:0"></div>
                                    </div>
                                </div>
                            <?php 
                            endif;
                            ?>
                            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        </div>
						<div class="clearer"></div>
            </div>
            <?php
                if(($i % 3) == 0 || $i == $_collectionSize){
            ?>
            </div>
            <?php
                }
            ?>
        <?php endforeach; ?>
		        </div>
        <script type="text/javascript">
    jQuery(function($){     
        var sidebar_owl = $(".small-list.sidebar-list.owl-carousel.owl-top-narrow");
        sidebar_owl.owlCarousel({
            lazyLoad: true,
            singleItem: true,
            responsiveRefreshRate: 50,
            slideSpeed: 200,
            paginationSpeed: 500,
            scrollPerPage: true,
            stopOnHover: true,
            rewindNav: true,
            rewindSpeed: 600,
            pagination: false,
            navigation: true,
            navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]           
        });
     
    });
</script>
    </div>
</div>
<?php endif; ?>
