<?php $_items = $this->getFlatCollection(); ?>

<div class="container main-container vendor-container">
    <h1 class="text-center"><?php echo $this->__('Product Import File Status') ?></h1>
    <div class="row">
        <div class="col-md-12">
            <form name="report_filter" id="report_filter" action="<?php echo Mage::getUrl('*/*/*') ?>" method="post" enctype="multipart/form-data">
                <div class="row">

                    <div class="col-md-2">
                        <input type="text" class="form-control datepicker input-text input-text validate-date" name="from" value="<?php echo $this->escapeHtml($this->getRequest()->getPost('from', '')); ?>" placeholder=<?php echo $this->__('From')?>/>
                    </div>
                    <div class="col-md-2">
                        <input type="text" class="form-control datepicker input-text input-text validate-date" name="to" value="<?php echo $this->escapeHtml($this->getRequest()->getPost('to', '')); ?>" placeholder=<?php echo $this->__('To')?>/>
                    </div>
                    <div class="col-md-2">
                        <select name="status"  placeholder="From">
                            <option value="5"> Status</option>
                            <?php
                                $statuArray = $this->getImportStatus();
                                foreach($statuArray as $key=>$status) {
                            ?>
                            <option value="<?php echo $key ?>"<?php echo $key ==  $this->getRequest()->getPost('status', '') ? ' selected="selected"' : ""; ?>><?php echo $status ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-1">
                        <input type="submit" name="submit" class="btn btn-primary btn-sm" value="<?php echo $this->__('Filter') ?>" />
                    </div>

                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class='table-responsive'>
                <table class="table table-striped">
                    <thead>
                    <th><?php echo $this->__('File Id #') ?></th>
                    <th><?php echo $this->__('File Name') ?></th>
                    <th><?php echo $this->__('Attribute Set Name') ?></th>
                    <th><?php echo $this->__('Uploaded On') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                    </thead>
                    <tbody>
                    <?php if($_items->count()): ?>
                        <?php foreach($_items AS $_item): ?>
                            <tr class="item">
                                <td>#<?php echo $_item->getId(); ?></td>
                                <td><?php echo $_item->getFileName(); ?></td>
                                <td><?php echo $_item->getAttributeSetName(); ?></td>
                                <td><?php echo $_item->getCreatedAt() ?></td>
                                <td><?php echo $this->statusHtml($_item->getStatus()); ?></td>

                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <td colspan="7"><?php echo $this->__("No results"); ?></td>
                    <?php endif; ?>
                    </tbody>
                    <tfoot>
                    <th><?php echo $this->__('File Id #') ?></th>
                    <th><?php echo $this->__('File Name') ?></th>
                    <th><?php echo $this->__('Attribute Set Name') ?></th>
                    <th><?php echo $this->__('Uploaded On') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                    </tfoot>
                </table>
                <?php
                echo $this->getLayout()->createBlock('core/template')
                    ->setTemplate('marketplace/order/index/pagination.phtml')
                    ->setCollection($_items)
                    ->toHtml() ?>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('report_filter');
    //]]>
    jQuery(document).ready(function($){
        jQuery('.datepicker').datepicker();

        jQuery('#report_filter input[type="submit"]').click(function(e){
            var actionExport = '<?php echo $this->getUrl('*/*/*') ?>';
            var form = jQuery('#report_filter');
            form.attr('action', actionExport);
            form.submit();
        });

    });
</script>
